In [38]:
# Exercici 1
# Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades.
# Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error
import numpy as np

def menor(lliste):
    if lliste.ndim > 1:
        print("Array té més d’una dimensió")
    else:
        # Mostrem valors si es array de 1 dimensió
        print("Valor de la mitjana:", np.mean(lliste))
        print("Valor de la mediana:", np.median(lliste))
        print("Valor de la desviació:", np.around(np.std(lliste),2))
        print("Valor mínim:", np.amin(lliste))
        print("Valor màxim:", np.amax(lliste))

# Mostrem valors si es array de 1 dimensió
lliste = np.array([1, 2, 3, 3, 5, 3])
menor(lliste)

# Mostrem error mes d'una dimensió
lliste = np.array([[1, 2, 3], [1, 2, 3]])
menor(lliste)

Valor de la mitjana: 2.8333333333333335
Valor de la mediana: 3.0
Valor de la desviació: 1.21
Valor mínim: 1
Valor màxim: 5
Array té més d’una dimensió


In [39]:
# Exercici 2
# Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.
import numpy as np
from numpy import random

def omplir(n):
    matriu = random.randint(100, size=(n,n))
    print(matriu)


# Mostrem els valors random de la matriu NxN
print(omplir(4))

[[31 16 69 67]
 [29 63 76 19]
 [14 85 17 90]
 [68 35 81 34]]
None


In [12]:
# Exercici 3
# Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.
import numpy as np

def calcularTotals(x):
    print("Totals fila:",np.sum(x, axis=1))
    print("Totals columna:",np.sum(x, axis=0))


lliste = np.array([[1, 2, 3], [10, 20, 30]])    

#Cridem al calcul de total per fila i columna    
calcularTotals(lliste)


Totals fila: [ 6 60]
Totals columna: [11 22 33]


In [37]:
# Exercici 4
# Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.
import numpy as np

def calcularCorrelacio(x,y):
    #Valors de sortida del coeficient de correlacio
    # Si r=0, no existeix relació lineal entre les dues variables
    # Si r>0, la relació és positiva. Si augmenta els valors d'una de les variables, augmenta els de l'altre
    # Si r<0, la relació és negativa. Si augmenta els valors d'una de les variables, disminueix els de l'altre        
    r = np.cov(x,y)[0,1] / (np.std(x)*np.std(y))   # Correlacio coeficient
    
    if r == 0:
        print("Si r=0, no existeix relació lineal entre les dues variables")
    elif r > 0 :
        print("Si r>0, la relació és positiva. Si augmenta els valors d'una de les variables, augmenta els de l'altre")
    else:
        print("Si r<0, la relació és negativa. Si augmenta els valors d'una de les variables, disminueix els de l'altre    ")
    
    print("Valor correlacio coeficient: " + str(r))
    
#Cridem al calcul del coeficient de correlacio

#dadesAlcada = np.array([1.25, 1.28, 1.27, 1.21, 1.22, 1.29, 1.30, 1.24, 1.27, 1.29, 1.25, 1.28, 1.27, 1.21, 1.22, 1.29, 1.30, 1.24, 1.27, 1.29, 1.25, 1.28, 1.27, 1.21, 1.22, 1.29, 1.30, 1.24, 1.27, 1.29])
#dadesPes = np.array([32,33,34,30,32,35,34,32,32,35,33,35,34,30,33,34,35,32,33,33,33,34,34,31,32,34,34,31,35,34])

dadesAlcada= np.random.rand(7) # np.array([1.25, 1.28, 1.27, 1.21])
dadesPes= np.random.rand(7)    # np.array([32,33,34,30])

calcularCorrelacio(dadesAlcada,dadesPes)

Si r<0, la relació és negativa. Si augmenta els valors d'una de les variables, disminueix els de l'altre    
Valor correlacio coeficient: -0.34131410440956356
