In [3]:
# Exercici 1
import numpy as np

def menor(lliste):
	if lliste.ndim > 1:
		print("Array té més d’una dimensió")
		return None, None
	# return np.mean(lliste)
	return np.unique(lliste, return_counts=True)

lliste = np.array([1, 2, 3, 3, 5, 3])
#lliste = np.array([[1, 2], [3, 4]])

valors, repeticions = menor(lliste)

# Mostrem valors si es array de 1 dimensió
if not valors is None:
	print(valors)  # valor
	print(repeticions)  # Vegades que es repeteixen

[1 2 3 5]
[1 1 3 1]


In [1]:
#Exercici 2
# Llibreria per fer ramdom
from random import randint

def omplir(n):
	matriu=[]

	for r in range(n):
		fila= []

		for c in range(n):
			fila.append(randint(1,100))

		matriu.append(fila)

	return matriu

# Mostrem els valors random de la matriu NxN
print(omplir(4))

[[20, 2, 48, 72], [67, 26, 78, 75], [14, 62, 12, 22], [90, 39, 67, 81]]


In [3]:
#Exercici 3
import numpy as np
# Llibreria per dataframes
import pandas as pd

dades = np.random.randn(2, 2)

dataframe = pd.DataFrame(dades, index=['Fila1', 'Fila2'],
                         columns=['Columna1', 'Columna2'])

def calcularTotals(dataframe):
    # totals per columna
    print (dataframe.sum())
    # totals per fila
    print(dataframe.sum(axis=1))

#Cridem al calcul de total per fila i columna
calcularTotals(dataframe)

Columna1   -1.107803
Columna2    0.064567
dtype: float64
Fila1    0.846976
Fila2   -1.890212
dtype: float64


In [2]:
#Exercici 4
import numpy as np

dades = np.random.randn(5, 3)

def calcularCorrelacio(dades):

    print (np.corrcoef(dades))     # Correlacio coeficient
    #print(np.corrcoef(dades[0], dades[1]))     # Correlacio coeficient

#Cridem al calcul del coeficient de correlacio
calcularCorrelacio(dades)


[[ 1.         -0.0514849   0.95883683 -0.36889338 -0.67618771]
 [-0.0514849   1.         -0.33294666  0.94723147 -0.70093885]
 [ 0.95883683 -0.33294666  1.         -0.61763915 -0.43915374]
 [-0.36889338  0.94723147 -0.61763915  1.         -0.43532795]
 [-0.67618771 -0.70093885 -0.43915374 -0.43532795  1.        ]]
